version: "3.3"

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gobarber
      POSTGRES_PASSWORD: gobarber_pas
      POSTGRES_DB: gobarber
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gobarber

